// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Module4PR2.Context;

#nullable disable

namespace Module4PR2.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230120083632_SeedDb")]
    partial class SeedDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Module4PR2.Entities.Instances.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ClientId");

                    b.ToTable("Client", (string)null);

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Email = "tarasmelnyk@pochta.tam",
                            FirstName = "Taras",
                            LastName = "Melnyk"
                        },
                        new
                        {
                            ClientId = 2,
                            Email = "igorlopushko@pochta.tut",
                            FirstName = "Igor",
                            LastName = "Lopushko"
                        },
                        new
                        {
                            ClientId = 3,
                            Email = "ronaldo@cr7.siuuu",
                            FirstName = "Cristiano",
                            LastName = "Ronaldo",
                            Phone = "07777777777"
                        },
                        new
                        {
                            ClientId = 4,
                            Email = "ford@car.usa",
                            FirstName = "Henry",
                            LastName = "Ford",
                            Phone = "9852455792"
                        },
                        new
                        {
                            ClientId = 5,
                            Email = "physics@invent.usa",
                            FirstName = "Nikola",
                            LastName = "Tesla"
                        });
                });

            modelBuilder.Entity("Module4PR2.Entities.Instances.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("HiredDate")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("OfficeId");

                    b.HasIndex("TitleId");

                    b.ToTable("Employee", (string)null);

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            DateOfBirth = new DateTime(1955, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Steve",
                            HiredDate = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jobs",
                            OfficeId = 1,
                            TitleId = 1
                        },
                        new
                        {
                            EmployeeId = 2,
                            DateOfBirth = new DateTime(1984, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mark",
                            HiredDate = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Zuckerberg",
                            OfficeId = 1,
                            TitleId = 4
                        },
                        new
                        {
                            EmployeeId = 3,
                            DateOfBirth = new DateTime(1955, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bill",
                            HiredDate = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gates",
                            OfficeId = 1,
                            TitleId = 2
                        },
                        new
                        {
                            EmployeeId = 4,
                            DateOfBirth = new DateTime(1971, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Elon",
                            HiredDate = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Musk",
                            OfficeId = 1,
                            TitleId = 3
                        },
                        new
                        {
                            EmployeeId = 5,
                            FirstName = "James",
                            HiredDate = new DateTime(2022, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Norrington",
                            OfficeId = 2,
                            TitleId = 1
                        },
                        new
                        {
                            EmployeeId = 6,
                            DateOfBirth = new DateTime(1950, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Steve",
                            HiredDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wozniak",
                            OfficeId = 2,
                            TitleId = 2
                        },
                        new
                        {
                            EmployeeId = 7,
                            FirstName = "Davy",
                            HiredDate = new DateTime(2022, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jones",
                            OfficeId = 3,
                            TitleId = 1
                        },
                        new
                        {
                            EmployeeId = 8,
                            FirstName = "Bill",
                            HiredDate = new DateTime(2022, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Turner",
                            OfficeId = 3,
                            TitleId = 4
                        },
                        new
                        {
                            EmployeeId = 9,
                            FirstName = "Jack",
                            HiredDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sparrow",
                            OfficeId = 4,
                            TitleId = 1
                        },
                        new
                        {
                            EmployeeId = 10,
                            FirstName = "Joshamee",
                            HiredDate = new DateTime(2022, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gibbs",
                            OfficeId = 4,
                            TitleId = 3
                        });
                });

            modelBuilder.Entity("Module4PR2.Entities.Instances.EmployeeProject", b =>
                {
                    b.Property<int>("EmployeeProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeProjectId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("money");

                    b.Property<DateTime?>("StartedDate")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.HasKey("EmployeeProjectId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("EmployeeProject", (string)null);

                    b.HasData(
                        new
                        {
                            EmployeeProjectId = 1,
                            EmployeeId = 3,
                            ProjectId = 1,
                            Rate = 500m,
                            StartedDate = new DateTime(2023, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeProjectId = 2,
                            EmployeeId = 6,
                            ProjectId = 2,
                            Rate = 200m,
                            StartedDate = new DateTime(2022, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeProjectId = 3,
                            EmployeeId = 6,
                            ProjectId = 3,
                            Rate = 200m,
                            StartedDate = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeProjectId = 4,
                            EmployeeId = 10,
                            ProjectId = 4,
                            Rate = 1000m,
                            StartedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeProjectId = 5,
                            EmployeeId = 4,
                            ProjectId = 5,
                            Rate = 700m,
                            StartedDate = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeProjectId = 6,
                            EmployeeId = 8,
                            ProjectId = 11,
                            Rate = 2200m,
                            StartedDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Module4PR2.Entities.Instances.Office", b =>
                {
                    b.Property<int>("OfficeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfficeId"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OfficeId");

                    b.ToTable("Office", (string)null);

                    b.HasData(
                        new
                        {
                            OfficeId = 1,
                            Location = "Kyiv",
                            Title = "Capital"
                        },
                        new
                        {
                            OfficeId = 2,
                            Location = "Kharkiv",
                            Title = "Interceptor"
                        },
                        new
                        {
                            OfficeId = 3,
                            Location = "Lviv",
                            Title = "Flying Dutchman"
                        },
                        new
                        {
                            OfficeId = 4,
                            Location = "Dnipro",
                            Title = "Black Pearl"
                        });
                });

            modelBuilder.Entity("Module4PR2.Entities.Instances.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("money");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("StartedDate")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectId");

                    b.HasIndex("ClientId");

                    b.ToTable("Project", (string)null);

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            Budget = 500m,
                            ClientId = 1,
                            Name = "Internet auction",
                            StartedDate = new DateTime(2023, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProjectId = 2,
                            Budget = 200m,
                            ClientId = 2,
                            Name = "Module 4 Homework 3",
                            StartedDate = new DateTime(2022, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProjectId = 3,
                            Budget = 200m,
                            ClientId = 2,
                            Name = "Module 4 Practice 1",
                            StartedDate = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProjectId = 4,
                            Budget = 1000m,
                            ClientId = 3,
                            Name = "Instagram Bot",
                            StartedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProjectId = 5,
                            Budget = 700m,
                            ClientId = 4,
                            Name = "Ford Focus",
                            StartedDate = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProjectId = 6,
                            Budget = 600m,
                            ClientId = 4,
                            Name = "Ford Fiesta",
                            StartedDate = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProjectId = 7,
                            Budget = 750m,
                            ClientId = 4,
                            Name = "Ford Mondeo",
                            StartedDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProjectId = 8,
                            Budget = 1500m,
                            ClientId = 4,
                            Name = "Ford Mustang",
                            StartedDate = new DateTime(2022, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProjectId = 9,
                            Budget = 2000m,
                            ClientId = 5,
                            Name = "Electro magnetic motor",
                            StartedDate = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProjectId = 10,
                            Budget = 2500m,
                            ClientId = 5,
                            Name = "Dynamo electric machine",
                            StartedDate = new DateTime(2022, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProjectId = 11,
                            Budget = 2200m,
                            ClientId = 5,
                            Name = "Thermo magnetic motor",
                            StartedDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Module4PR2.Entities.Instances.Title", b =>
                {
                    b.Property<int>("TitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TitleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TitleId");

                    b.ToTable("Title", (string)null);

                    b.HasData(
                        new
                        {
                            TitleId = 1,
                            Name = "Project Manager"
                        },
                        new
                        {
                            TitleId = 2,
                            Name = ".NET Developer"
                        },
                        new
                        {
                            TitleId = 3,
                            Name = "Database Administrator"
                        },
                        new
                        {
                            TitleId = 4,
                            Name = "Frontend Developer"
                        });
                });

            modelBuilder.Entity("Module4PR2.Entities.Instances.Employee", b =>
                {
                    b.HasOne("Module4PR2.Entities.Instances.Office", "Office")
                        .WithMany("Employees")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module4PR2.Entities.Instances.Title", "Title")
                        .WithMany("Employees")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Module4PR2.Entities.Instances.EmployeeProject", b =>
                {
                    b.HasOne("Module4PR2.Entities.Instances.Employee", "Employee")
                        .WithMany("EmployeeProjects")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module4PR2.Entities.Instances.Project", "Project")
                        .WithMany("EmployeeProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Module4PR2.Entities.Instances.Project", b =>
                {
                    b.HasOne("Module4PR2.Entities.Instances.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Module4PR2.Entities.Instances.Client", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Module4PR2.Entities.Instances.Employee", b =>
                {
                    b.Navigation("EmployeeProjects");
                });

            modelBuilder.Entity("Module4PR2.Entities.Instances.Office", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Module4PR2.Entities.Instances.Project", b =>
                {
                    b.Navigation("EmployeeProjects");
                });

            modelBuilder.Entity("Module4PR2.Entities.Instances.Title", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
